'copied form aws


!define TECHN_FONT_SIZE 12

!definelong Entity(e_alias, e_label, e_techn, e_color, e_sprite, e_stereo)
rectangle "==e_label\n<color:e_color><$e_sprite></color>\n//<size:TECHN_FONT_SIZE>[e_techn]</size>//" <<e_stereo>> as e_alias
!enddefinelong


sprite $cog [48x48/16z] {
tTH9biCm20JGmiAZ9BZ_QNlk49lKizRvoqHpWV5-gl-f627-81XGOdp1W2N6pnYmnVWD0uuOVu1IEnJVLd-oufiUfhZexjvNKVCJcsNv-GjdgzzOqvjpEOlT
R-qf8YQ7rtn0YxVqCriBK5RpCoN7EI8vSg1YQNYQO0L1QlmEX5YdIgwo7CpAAY-McbxrWY7nF-JNmV6sgm2YI6oq1_bzEMdvFJEM5qFhWUFrzgTEoEBqwHef
Mj8lUyJI5O7repx7c0ubjBr9lQr-SIsJhlnxnSVpx-6KpiCSvBxCHjwJcM_o8k4jj1vUPs62GJNAzFry0W
}


sprite $email [48x48/16z] {
xTG55iCm30DGbTc-_sttA7fpU8pQoZ-9YtXz_catBMPjGQur4JROj2ghyrgPSzzBJihWUs1EymK8FRezhlSEKG-CCJu14Ryr0D2iXfhznhCVUzuoS5phMQSv
xmNWULaV7W_RqyV7PtsX3yzlSqjbefxzSfo2PzqyZwYtMNYU9S_p7aJhFFDh_k-l_HwsKiEbWKkpLlJUuFNvvmG
}

!define Message(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #D86613, email, Message)

!define Process(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #D86613, cog, Process)

