version: '2'

services:

  plantuml:
    
    container_name: pragmaticMDA-plantuml
    image: plantuml/plantuml-server:jetty
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ALLOW_PLANTUML_INCLUDE=true
      - _JAVA_OPTIONS="-Dplantuml.include.path=/include"
    volumes:
      - ./include:/include