version: '2'

services:

  db:
    env_file:
      - credentials.env
    hostname: db
    container_name: pragmaticMDA-db
    image: mysql
    restart: always
    ports:
      - "3306:3306"      
    volumes:
      - pragmaticMDA-db-data:/var/lib/mysql
  
volumes:
  pragmaticMDA-db-data: